/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tp3;



import java.net.MalformedURLException;
import java.net.URL;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JProgressBar;
import javax.swing.SwingUtilities;

/**
 *
 * @author Loic.FOREST
 */
public class JPanelCombat extends javax.swing.JPanel {
    
    private Ennemies ennemie;
    private Heros heros;
    private boolean soin = true;
    private boolean end = false;
    JFrame fenetre;
    
    
    /**
     * Creates new form JPanelCombat
     */
    public JPanelCombat(JFrame fen, Heros heros){
        this.fenetre = fenetre;
        this.heros = heros;
        this.ennemie = Random.ennemie();
        
        initComponents();
        
        pvEnnemi.setMaximum(this.ennemie.PVmax);
        pvEnnemi.setValue(this.ennemie.PV);
        pvHeros.setMaximum(this.heros.PVmax);
        pvHeros.setValue(this.heros.PV);

        SwingUtilities.updateComponentTreeUI(this.fenetre);
        
        
    }
    
    public JPanelCombat(Heros hero){
        
        System.out.println();
        this.fenetre = new JFrame();
        this.heros = hero;
        this.ennemie = Random.ennemie();
        
        System.out.println(this.ennemie.getNom());
        this.fenetre.setSize(600, 600);
        this.fenetre.setVisible(true);
        
        initComponents();
        
        ennemiNom.setText(this.ennemie.getNom());
        pvEnnemi.setMaximum(this.ennemie.PVmax);
        pvEnnemi.setValue(this.ennemie.PV);
        pvHeros.setMaximum(this.heros.PVmax);
        pvHeros.setValue(this.heros.PV);
        
        fenetre.setContentPane(this);
        
        SwingUtilities.updateComponentTreeUI(this.fenetre);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        soinBtn = new java.awt.Button();
        attBtn = new java.awt.Button();
        fuirBtn = new java.awt.Button();
        caBtn = new java.awt.Button();
        cpBtn = new java.awt.Button();
        feinteBtn = new java.awt.Button();
        message = new java.awt.Label();
        pvHeros = new javax.swing.JProgressBar();
        pvEnnemi = new javax.swing.JProgressBar();
        herosNom = new java.awt.Label();
        ennemiNom = new java.awt.Label();
        ennemiImage = new javax.swing.JPanel();

        setMaximumSize(new java.awt.Dimension(300, 300));
        setMinimumSize(new java.awt.Dimension(300, 300));
        setOpaque(false);

        soinBtn.setLabel("Se soigner");
        soinBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                soinBtnActionPerformed(evt);
            }
        });

        attBtn.setLabel("Attaque");
        attBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                attBtnActionPerformed(evt);
            }
        });

        fuirBtn.setLabel("Fuir");
        fuirBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fuirBtnActionPerformed(evt);
            }
        });

        caBtn.setLabel("Contre Attaque");
        caBtn.setVisible(false);
        caBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caBtnActionPerformed(evt);
            }
        });

        cpBtn.setLabel("Coup Puissant");
        cpBtn.setVisible(false);
        cpBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cpBtnActionPerformed(evt);
            }
        });

        feinteBtn.setLabel("Feinte");
        feinteBtn.setVisible(false);
        feinteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                feinteBtnActionPerformed(evt);
            }
        });

        message.setAlignment(java.awt.Label.CENTER);
        message.setText("Que voulez-vous faire ?");

        pvHeros.setToolTipText("");

        herosNom.setText("Vos PV");

        ennemiNom.setText("Les PV de l'ennemi");

        ennemiImage.setMaximumSize(new java.awt.Dimension(200, 200));
        ennemiImage.setMinimumSize(new java.awt.Dimension(200, 200));
        ennemiImage.setPreferredSize(new java.awt.Dimension(200, 200));

        javax.swing.GroupLayout ennemiImageLayout = new javax.swing.GroupLayout(ennemiImage);
        ennemiImage.setLayout(ennemiImageLayout);
        ennemiImageLayout.setHorizontalGroup(
            ennemiImageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        ennemiImageLayout.setVerticalGroup(
            ennemiImageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(attBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)
                                .addComponent(soinBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(fuirBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(ennemiImage, javax.swing.GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 205, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pvEnnemi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ennemiNom, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pvHeros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(herosNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(message, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cpBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(caBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(feinteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pvEnnemi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ennemiNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(ennemiImage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 179, Short.MAX_VALUE)
                .addComponent(herosNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pvHeros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(message, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(attBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fuirBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(soinBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cpBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(feinteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(caBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(75, 75, 75))
        );
    }// </editor-fold>//GEN-END:initComponents

    public void setjPanel1() {

        this.ennemiImage = ennemiImage;
    }

    public void setSoinBtn(java.awt.Button soinBtn) {
        this.soinBtn = soinBtn;
    }

    public java.awt.Button getSoinBtn() {
        return soinBtn;
    }
    
    public JProgressBar getPvEnnemi() {
        return pvEnnemi;
    }

    public JProgressBar getPvHeros() {
        return pvHeros;
    }

    public void setPvEnnemi(JProgressBar pvEnnemi) {
        this.pvEnnemi = pvEnnemi;
    }

    public void setPvHeros(JProgressBar pvHeros) {
        this.pvHeros = pvHeros;
    }

    private void attBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_attBtnActionPerformed
        this.cpBtn.setVisible(true);
        this.caBtn.setVisible(true);
        this.feinteBtn.setVisible(true);
        this.attBtn.setVisible(false);
        this.soinBtn.setVisible(false);
        this.fuirBtn.setVisible(false);
        SwingUtilities.updateComponentTreeUI(this.fenetre);
    }//GEN-LAST:event_attBtnActionPerformed

    private void soinBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_soinBtnActionPerformed
        
        soinBtn.setEnabled(false);
        double s = this.heros.seSoigner();
        
        Runnable runner = new Runnable()
            {
                public void run() {
                    for (int i = 0; i <= s; i++) {
                        pvHeros.setValue(pvHeros.getValue()+1);
                        
                        try {
                            Thread.sleep(100);
                        } catch(InterruptedException e) {
                            Thread.currentThread().interrupt();
                            break;
                        }
                    }
                }
            };
            Thread t = new Thread(runner, "Code Executer");
            t.start();  
        
        System.out.print("Vous récupérez "+(int)s+" pv.");
    }//GEN-LAST:event_soinBtnActionPerformed

    private void cpBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cpBtnActionPerformed
   
        int t = Random.typeAttaque();
        int dmg = 0;
        switch(t) {
            case 1 : System.out.print("L'ennemi et vous portez un coup puissant. Vous vous blessez tous les deux.\n");
                            int hdmg = this.heros.force*(Random.dice(6))/4;
                            dmg = this.ennemie.force*(Random.dice(6))/4;
                            ennemie.setMoinsPV(hdmg);
                            heros.setMoinsPV(dmg);
                            System.out.print("Il perd "+hdmg+" pv.");
                            this.majPvDmg(hdmg,0);
                            System.out.print("Vous perdez "+dmg+" pv.");
                            this.majPvDmg(dmg,1);
            break;
            case 2 : System.out.print("Vous tentez un coup puissant mais l'ennemi arrive à vous contrez ! Il vous touche !\n");
                            int rand = Random.dice(2)-1;
                            if (rand == 1){
                                dmg = this.heros.force+10;
                            } else {
                                dmg = 10;
                            }
                            heros.setMoinsPV(dmg);
                            System.out.print("Vous perdez "+dmg+" pv.");
                            this.majPvDmg(dmg,1);
            break;
            case 3 : System.out.print("L'ennemi tente maladroitement une attaque, vous le punissez ! Vous le touchez !\n");
                            dmg = this.heros.force*(Random.dice(6))/4;
                            ennemie.setMoinsPV(dmg);
                            System.out.print("Il perd "+dmg+" pv.");
                            this.majPvDmg(dmg,0);
            break;
        }
        this.cpBtn.setVisible(false);
        this.caBtn.setVisible(false);
        this.feinteBtn.setVisible(false);
        this.attBtn.setVisible(true);
        this.soinBtn.setVisible(true);
        this.fuirBtn.setVisible(true);
        SwingUtilities.updateComponentTreeUI(this.fenetre);
    }//GEN-LAST:event_cpBtnActionPerformed

    private void fuirBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fuirBtnActionPerformed
        boolean b = Random.fuite(ennemie);
        if (b) {
            System.out.print("Vous prenez la fuite ...");
            
        }
        else {
            System.out.print("Fuite impossible ... L'ennemi vous rattrape et vous blesse.");
            heros.setMoinsPV(this.ennemie.force);
            System.out.print("Vous perdez "+this.ennemie.getForce()+" pv.");
            if(heros.getPV() > 0) {
            } else {
                
            }
            
        }
    }//GEN-LAST:event_fuirBtnActionPerformed

    private void caBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caBtnActionPerformed
        int t = Random.typeAttaque();
        int dmg;
        switch(t) {
            case 1 :
                            int rand = Random.dice(2)-1;
                            System.out.print("L'ennemi porte un coup puissant mais vous contre-attaquez magistralement ! Vous le touchez !\n");
                            if (rand == 1){
                                dmg = this.ennemie.force+10;
                            } else {
                                dmg = 10;
                            }
                            ennemie.setMoinsPV(dmg);
                            System.out.print("Il perd "+dmg+" pv.");
                            this.majPvDmg(dmg,0);
            break;

            case 2 : System.out.print("Votre ennemi et vous-même attendez patiemment le coup de l'autre ...\n");
            break;

            case 3 : System.out.print("L'ennemi semble vouloir porter un coup violent, vous tentez une parade mais il vous porte un coup bas au dernier moment ! Il vous touche !\n");
                            dmg = Random.dice(11)+9;
                            dmg = dmg * this.heros.getPV()/this.ennemie.getPV();
                            heros.setMoinsPV(dmg);
                            System.out.print("Vous perdez "+dmg+" pv.");
                            this.majPvDmg(dmg,1);
            break;
        }
        this.cpBtn.setVisible(false);
        this.caBtn.setVisible(false);
        this.feinteBtn.setVisible(false);
        this.attBtn.setVisible(true);
        this.soinBtn.setVisible(true);
        this.fuirBtn.setVisible(true);
        SwingUtilities.updateComponentTreeUI(this.fenetre);
        
    }//GEN-LAST:event_caBtnActionPerformed

    private void feinteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_feinteBtnActionPerformed
        
        int t = Random.typeAttaque();
        int dmg = 0;
        switch(t) {
        case 3 : System.out.print("L'ennemi porte un coup puissant, votre feinte est inutile ! Il vous touche !\n");
                        dmg = this.ennemie.force*(Random.dice(6))/4;
                        heros.setMoinsPV(dmg);
                        System.out.print("Vous perdez "+dmg+" pv.");
                        this.majPvDmg(dmg,1);
        break;
        case 2 : System.out.print("Vous simulez une attaque, l'ennemi manque sa parade et vous lui portez un coup ! Vous le touchez !\n");
                        dmg = Random.dice(11)+9;
                        dmg = dmg * this.ennemie.getPV()/this.heros.getPV()+5;
                        ennemie.setMoinsPV(dmg);
                        System.out.print("Il perd "+dmg+" pv.");
                        this.majPvDmg(dmg,0);
        break;
        case 1 : System.out.print("Apres un échange de coups spectaculaire... \n");
                        int rand = Random.dice(2)-1;
                        dmg = Random.dice(11)+9;
                        if (rand == 1){
                            System.out.print("... vous réussissez à blesser l'ennemi !\n");
                            dmg = (this.ennemie.getPV()/this.heros.getPV()*dmg);
                            ennemie.setMoinsPV(dmg);
                            System.out.print("Il perd "+dmg+" pv.");
                            this.majPvDmg(dmg,0);
                        } else {
                            System.out.print("... vous vous faites toucher par l'ennemi !\n");
                            dmg = (this.heros.getPV()/this.ennemie.getPV()*dmg);
                            heros.setMoinsPV(dmg);
                            System.out.print("Vous perdez "+dmg+" pv.");
                            this.majPvDmg(dmg,1);
                        }
        break;
      }
        this.cpBtn.setVisible(false);
        this.caBtn.setVisible(false);
        this.feinteBtn.setVisible(false);
        this.attBtn.setVisible(true);
        this.soinBtn.setVisible(true);
        this.fuirBtn.setVisible(true);
        SwingUtilities.updateComponentTreeUI(this.fenetre);
    }//GEN-LAST:event_feinteBtnActionPerformed
    
    public void majPvDmg(int dmg, int target){
        
        if (target == 0) {

                Runnable runner = new Runnable()
            {
                public void run() {
                    for (int i = 0; i <= dmg; i++) {
                        System.out.println(pvEnnemi.getValue());
                        pvEnnemi.setValue(pvEnnemi.getValue()-1);
                        try {
                            Thread.sleep(100);
                        } catch(InterruptedException e) {
                            Thread.currentThread().interrupt();
                            break;
                        }
                        
                    }
                }
            };
            Thread t = new Thread(runner, "Code Executer");
            t.start();  
        }  else if (target == 1){
           Runnable runner = new Runnable()
            {
                public void run() {
                    for (int i = 0; i <= dmg; i++) {
                        pvHeros.setValue(pvHeros.getValue()-1);
                        
                        try {
                            Thread.sleep(100);
                        } catch(InterruptedException e) {
                            Thread.currentThread().interrupt();
                            break;
                        }
                    }
                }
            };
            Thread t = new Thread(runner, "Code Executer");
            t.start();   
        }
    }
    
    
        

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button attBtn;
    private java.awt.Button caBtn;
    private java.awt.Button cpBtn;
    private javax.swing.JPanel ennemiImage;
    private java.awt.Label ennemiNom;
    private java.awt.Button feinteBtn;
    private java.awt.Button fuirBtn;
    private java.awt.Label herosNom;
    private java.awt.Label message;
    private javax.swing.JProgressBar pvEnnemi;
    private javax.swing.JProgressBar pvHeros;
    private java.awt.Button soinBtn;
    // End of variables declaration//GEN-END:variables
}
